import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createTheme, MantineProvider } from "@mantine/core";
import { ReduxProvider } from "@/src/providers/ReduxProvider";
import NextAuthSessionProvider from "@/src/providers/NextAuthSessionProvider";
import GoogleAuthProvider from "@/src/providers/GoogleOAuthProvider";
import { fetchMe } from "@/src/services/fetchMe";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/charts/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyHub",
  description: "Generated by create next app",
};

const theme = createTheme({
  colors: {},
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchMe();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GoogleAuthProvider>
          <NextAuthSessionProvider>
            <ReduxProvider>
              <MantineProvider theme={theme} defaultColorScheme="light">
                {children}
              </MantineProvider>
            </ReduxProvider>
          </NextAuthSessionProvider>
        </GoogleAuthProvider>
      </body>
    </html>
  );
}
