import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { createTheme, MantineProvider } from "@mantine/core";
import { ReduxProvider } from "@/src/providers/ReduxProvider";
import NextAuthSessionProvider from "@/src/providers/NextAuthSessionProvider";
import GoogleAuthProvider from "@/src/providers/GoogleOAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GoogleAuthProvider>
          <NextAuthSessionProvider>
            <ReduxProvider>
              <MantineProvider theme={theme}>{children}</MantineProvider>
            </ReduxProvider>
          </NextAuthSessionProvider>
        </GoogleAuthProvider>
      </body>
    </html>
  );
}
